Repository dlang/ci, pull requests merged in 2018-09, with the labels that each got.

#303 improve buildkite agent config
  ansible/ci.yml
  ansible/roles/buildkite_agent/defaults/main.yml
  ansible/roles/buildkite_agent/handlers/main.yml
  ansible/roles/buildkite_agent/tasks/main.yml
Labels: WIP, auto-merge

#307 Strip meson build
  buildkite/build_project.sh
Labels: WIP

#310 remove unused Jenkins bits
  Jenkinsfile
  ansible/roles/jenkins_slave/handlers/main.yml
  ansible/roles/jenkins_slave/tasks/main.yml
  ansible/roles/jenkins_slave/templates/jenkins.service.j2
  plugins.xml
  vars/runPipeline.groovy
Labels: auto-merge
